version: "3.7"

#    This Source Code Form is subject to the terms of the Mozilla Public License,
#    v. 2.0. If a copy of the MPL was not distributed with this file, You can
#    obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
#    the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
#    
#    Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
#    graphic logo is a trademark of OpenMRS Inc.

services:
    db:
        ports:
            - "3306:3306"
        restart: "no"

    openmrs-core:
        image: openmrs/openmrs-core:${TAG:-dev}
        build:
            target: dev
            context: .
        ports:
            - "8080:8080"
            - "8000:8000"
        volumes:
            - ~/.m2:/root/.m2
        restart: "no"
